### ISSUE TITLE
Cannot install by nuget in .NET 4.5 project

### ISSUE THREAD

**Issue by nskiro** [2captcha/2captcha-csharp#1]
Hello,

I can not install package by nuget because my project target framework is .NET v4.5. Please help me fix this problem.

> Unable to resolve 'Microsoft.NETCore.App (>= 3.1.0)' for '.NETCoreApp,Version=v3.1'.

I setup **dotnet-sdk-3.1.402-win-x64** and when I run dotnet --version in cmd, I get **3.1.402**

Detail:

>.NET Core SDK (reflecting any global.json):
Version:   3.1.402
Commit:    9b5de826fd
Runtime Environment:
OS Name:     Windows
OS Version:  10.0.18363
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\3.1.402\
Host (useful for support):
Version: 3.1.8
Commit:  9c1330dedd
.NET Core SDKs installed:
3.1.402 [C:\Program Files\dotnet\sdk]
.NET Core runtimes installed:
Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
To install additional .NET Core runtimes or SDKs:
https://aka.ms/dotnet-download   

Thank you very much!

**Comment by topforce** [comment]
Please I have same problem How did you Solve this problem ?

**Comment by IlyaDhtvzGhbltn** [comment]
Framework 4.8. The same issue

**Comment by nhannguyen512** [comment]
Could not install package '2captcha-csharp 1.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by BryannLuna** [comment]
Same problem!

**Comment by topforce** [comment]
2Captcha-Csharp don't work with .netframwork , it's used just with .net Core .
