### ISSUE TITLE
Error TwoCaptcha Is name Space and you are using like a type .

### ISSUE THREAD

**Issue by topforce** [2captcha/2captcha-csharp#2]
Hello 
When instanciate twocaptcha class like this 

```csharp
TwoCaptcha solver = new TwoCaptcha("my key");
```

Error TwoCaptcha Is name Space and you are using like a type .

so i solved this error by using like this : 

```csharp
TwoCaptcha.Twocaptcha solver = new Twocaptcha.TwoCaptcha("Mykey");
```

Thank you to fix it next Version .

**Comment by The-Discord-Programs-Guy** [comment]
same

**Comment by The-Discord-Programs-Guy** [comment]
thank you bro!

**Comment by mehmetarslann** [comment]
I was getting the same error. Thank you for feedback.

**Comment by topforce** [comment]
> 
> 
> I was getting the same error. Thank you for feedback.

You are welcome , Did you try my solutions ?

**Comment by peterchen145** [comment]
Got the same issue. Thanks for sharing.
