### ISSUE TITLE
I can't solve Geetest Captcha

### ISSUE THREAD

**Issue by hoangvu0905** [2captcha/2captcha-csharp#3]
I don't know what I did wrong.
I am testing the captcha geetest solve from https://2captcha.com/demo/geetest
I have replaced gt = 81388ea1fc187e0c335c0a8907ff2625, Challenge but it doesn't work.
Error occurred: ERROR_CAPTCHA_UNSOLVABLE

**Comment by ARAGRAGMED** [comment]
Have you solved this problem?

**Comment by sumukhah** [comment]
Facing the same issue!!

**Comment by Juanchobanano** [comment]
I'm also facing the same issue here.
