### ISSUE TITLE
Could not install package '2captcha-csharp 1.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### ISSUE THREAD

**Issue by BryannLuna** [2captcha/2captcha-csharp#5]
Could not install package '2captcha-csharp 1.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

issue!

**Comment by GenixZero** [comment]
it only works with .net core, not framework.
